// <auto-generated />
using System;
using HappyTrip.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HappyTrip.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220526142718_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HappyTrip.Models.Autobus", b =>
                {
                    b.Property<int>("idAutobus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("capacite")
                        .HasColumnType("int");

                    b.Property<int>("matricule")
                        .HasColumnType("int");

                    b.HasKey("idAutobus");

                    b.ToTable("Autobus");
                });

            modelBuilder.Entity("HappyTrip.Models.Chauffeur", b =>
                {
                    b.Property<int>("idChauffeur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cinChauffeur")
                        .HasColumnType("int");

                    b.Property<string>("nomChauffeur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typePermis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idChauffeur");

                    b.ToTable("Chauffeurs");
                });

            modelBuilder.Entity("HappyTrip.Models.Excursion", b =>
                {
                    b.Property<int>("idExcur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageExcur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lieuExcur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("prixExcur")
                        .HasColumnType("int");

                    b.HasKey("idExcur");

                    b.ToTable("Excursions");
                });

            modelBuilder.Entity("HappyTrip.Models.Voyage", b =>
                {
                    b.Property<int>("idVoyage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AutobusidAutobus")
                        .HasColumnType("int");

                    b.Property<int?>("ChauffeuridChauffeur")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDep")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRetour")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExcursionidExcur")
                        .HasColumnType("int");

                    b.Property<int>("idAutobus")
                        .HasColumnType("int");

                    b.Property<int>("idChauffeur")
                        .HasColumnType("int");

                    b.Property<int>("idExcur")
                        .HasColumnType("int");

                    b.HasKey("idVoyage");

                    b.HasIndex("AutobusidAutobus");

                    b.HasIndex("ChauffeuridChauffeur");

                    b.HasIndex("ExcursionidExcur");

                    b.ToTable("Voyages");
                });

            modelBuilder.Entity("HappyTrip.Models.Voyage", b =>
                {
                    b.HasOne("HappyTrip.Models.Autobus", "Autobus")
                        .WithMany("Voyages")
                        .HasForeignKey("AutobusidAutobus");

                    b.HasOne("HappyTrip.Models.Chauffeur", "Chauffeur")
                        .WithMany("Voyages")
                        .HasForeignKey("ChauffeuridChauffeur");

                    b.HasOne("HappyTrip.Models.Excursion", "Excursion")
                        .WithMany("Voyages")
                        .HasForeignKey("ExcursionidExcur");

                    b.Navigation("Autobus");

                    b.Navigation("Chauffeur");

                    b.Navigation("Excursion");
                });

            modelBuilder.Entity("HappyTrip.Models.Autobus", b =>
                {
                    b.Navigation("Voyages");
                });

            modelBuilder.Entity("HappyTrip.Models.Chauffeur", b =>
                {
                    b.Navigation("Voyages");
                });

            modelBuilder.Entity("HappyTrip.Models.Excursion", b =>
                {
                    b.Navigation("Voyages");
                });
#pragma warning restore 612, 618
        }
    }
}
